"""
generate_fund_master.py
=======================
Generates a realistic fund_master.csv dataset for the Bluestock Fintech
Mutual Fund Analytics project.

Includes AMFI scheme codes, fund houses, categories, sub-categories,
and risk grades for 30 large/mid/small cap Indian mutual fund schemes.

Usage:
    python scripts/generate_fund_master.py
"""

from pathlib import Path
import pandas as pd

PROJECT_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_PATH = PROJECT_ROOT / "data" / "raw" / "fund_master.csv"

FUND_MASTER_DATA = [
    # Large Cap Funds (schemes we already have NAV data for)
    {
        "scheme_code": 125497,
        "scheme_name": "HDFC Top 100 Fund - Direct Plan - Growth",
        "fund_house": "HDFC Mutual Fund",
        "scheme_type": "Open Ended Schemes",
        "scheme_category": "Equity Scheme",
        "scheme_sub_category": "Large Cap Fund",
        "risk_grade": "Very High",
        "aum_cr": 29874.50,
        "expense_ratio": 0.56,
        "launch_date": "2013-01-01",
    },
    {
        "scheme_code": 119551,
        "scheme_name": "SBI Bluechip Fund - Direct Plan - Growth",
        "fund_house": "SBI Mutual Fund",
        "scheme_type": "Open Ended Schemes",
        "scheme_category": "Equity Scheme",
        "scheme_sub_category": "Large Cap Fund",
        "risk_grade": "Very High",
        "aum_cr": 45231.20,
        "expense_ratio": 0.79,
        "launch_date": "2013-01-01",
    },
    {
        "scheme_code": 120503,
        "scheme_name": "ICICI Prudential Bluechip Fund - Direct Plan - Growth",
        "fund_house": "ICICI Prudential Mutual Fund",
        "scheme_type": "Open Ended Schemes",
        "scheme_category": "Equity Scheme",
        "scheme_sub_category": "Large Cap Fund",
        "risk_grade": "Very High",
        "aum_cr": 51380.75,
        "expense_ratio": 0.87,
        "launch_date": "2013-01-01",
    },
    {
        "scheme_code": 118632,
        "scheme_name": "Nippon India Large Cap Fund - Direct Plan - Growth",
        "fund_house": "Nippon India Mutual Fund",
        "scheme_type": "Open Ended Schemes",
        "scheme_category": "Equity Scheme",
        "scheme_sub_category": "Large Cap Fund",
        "risk_grade": "Very High",
        "aum_cr": 22156.80,
        "expense_ratio": 0.82,
        "launch_date": "2013-01-01",
    },
    {
        "scheme_code": 119092,
        "scheme_name": "Axis Bluechip Fund - Direct Plan - Growth",
        "fund_house": "Axis Mutual Fund",
        "scheme_type": "Open Ended Schemes",
        "scheme_category": "Equity Scheme",
        "scheme_sub_category": "Large Cap Fund",
        "risk_grade": "Very High",
        "aum_cr": 36742.10,
        "expense_ratio": 0.44,
        "launch_date": "2013-01-01",
    },
    {
        "scheme_code": 120841,
        "scheme_name": "Kotak Bluechip Fund - Direct Plan - Growth",
        "fund_house": "Kotak Mahindra Mutual Fund",
        "scheme_type": "Open Ended Schemes",
        "scheme_category": "Equity Scheme",
        "scheme_sub_category": "Large Cap Fund",
        "risk_grade": "Very High",
        "aum_cr": 8941.30,
        "expense_ratio": 0.52,
        "launch_date": "2013-01-01",
    },
    # Mid Cap Funds
    {
        "scheme_code": 120505,
        "scheme_name": "ICICI Prudential Midcap Fund - Direct Plan - Growth",
        "fund_house": "ICICI Prudential Mutual Fund",
        "scheme_type": "Open Ended Schemes",
        "scheme_category": "Equity Scheme",
        "scheme_sub_category": "Mid Cap Fund",
        "risk_grade": "Very High",
        "aum_cr": 4892.60,
        "expense_ratio": 0.95,
        "launch_date": "2013-01-01",
    },
    {
        "scheme_code": 119598,
        "scheme_name": "SBI Magnum Midcap Fund - Direct Plan - Growth",
        "fund_house": "SBI Mutual Fund",
        "scheme_type": "Open Ended Schemes",
        "scheme_category": "Equity Scheme",
        "scheme_sub_category": "Mid Cap Fund",
        "risk_grade": "Very High",
        "aum_cr": 18723.40,
        "expense_ratio": 0.85,
        "launch_date": "2013-01-01",
    },
    {
        "scheme_code": 120178,
        "scheme_name": "HDFC Mid-Cap Opportunities Fund - Direct Plan - Growth",
        "fund_house": "HDFC Mutual Fund",
        "scheme_type": "Open Ended Schemes",
        "scheme_category": "Equity Scheme",
        "scheme_sub_category": "Mid Cap Fund",
        "risk_grade": "Very High",
        "aum_cr": 61482.90,
        "expense_ratio": 0.74,
        "launch_date": "2013-01-01",
    },
    {
        "scheme_code": 118825,
        "scheme_name": "Nippon India Growth Fund - Direct Plan - Growth",
        "fund_house": "Nippon India Mutual Fund",
        "scheme_type": "Open Ended Schemes",
        "scheme_category": "Equity Scheme",
        "scheme_sub_category": "Mid Cap Fund",
        "risk_grade": "Very High",
        "aum_cr": 23411.20,
        "expense_ratio": 0.98,
        "launch_date": "2013-01-01",
    },
    # Small Cap Funds
    {
        "scheme_code": 125354,
        "scheme_name": "SBI Small Cap Fund - Direct Plan - Growth",
        "fund_house": "SBI Mutual Fund",
        "scheme_type": "Open Ended Schemes",
        "scheme_category": "Equity Scheme",
        "scheme_sub_category": "Small Cap Fund",
        "risk_grade": "Very High",
        "aum_cr": 25317.80,
        "expense_ratio": 0.62,
        "launch_date": "2013-01-01",
    },
    {
        "scheme_code": 120828,
        "scheme_name": "Kotak Small Cap Fund - Direct Plan - Growth",
        "fund_house": "Kotak Mahindra Mutual Fund",
        "scheme_type": "Open Ended Schemes",
        "scheme_category": "Equity Scheme",
        "scheme_sub_category": "Small Cap Fund",
        "risk_grade": "Very High",
        "aum_cr": 14893.50,
        "expense_ratio": 0.47,
        "launch_date": "2013-01-01",
    },
    {
        "scheme_code": 120587,
        "scheme_name": "Axis Small Cap Fund - Direct Plan - Growth",
        "fund_house": "Axis Mutual Fund",
        "scheme_type": "Open Ended Schemes",
        "scheme_category": "Equity Scheme",
        "scheme_sub_category": "Small Cap Fund",
        "risk_grade": "Very High",
        "aum_cr": 19654.30,
        "expense_ratio": 0.38,
        "launch_date": "2013-01-01",
    },
    # ELSS / Tax Saving
    {
        "scheme_code": 120586,
        "scheme_name": "Axis Long Term Equity Fund - Direct Plan - Growth",
        "fund_house": "Axis Mutual Fund",
        "scheme_type": "Open Ended Schemes",
        "scheme_category": "Equity Scheme",
        "scheme_sub_category": "ELSS",
        "risk_grade": "Very High",
        "aum_cr": 34218.70,
        "expense_ratio": 0.49,
        "launch_date": "2013-01-01",
    },
    {
        "scheme_code": 119598,
        "scheme_name": "SBI Long Term Equity Fund - Direct Plan - Growth",
        "fund_house": "SBI Mutual Fund",
        "scheme_type": "Open Ended Schemes",
        "scheme_category": "Equity Scheme",
        "scheme_sub_category": "ELSS",
        "risk_grade": "Very High",
        "aum_cr": 21098.40,
        "expense_ratio": 0.78,
        "launch_date": "2013-01-01",
    },
    # Flexi Cap / Multi Cap
    {
        "scheme_code": 100119,
        "scheme_name": "Parag Parikh Flexi Cap Fund - Direct Plan - Growth",
        "fund_house": "PPFAS Mutual Fund",
        "scheme_type": "Open Ended Schemes",
        "scheme_category": "Equity Scheme",
        "scheme_sub_category": "Flexi Cap Fund",
        "risk_grade": "Very High",
        "aum_cr": 68742.50,
        "expense_ratio": 0.55,
        "launch_date": "2013-05-24",
    },
    {
        "scheme_code": 119551,
        "scheme_name": "HDFC Flexi Cap Fund - Direct Plan - Growth",
        "fund_house": "HDFC Mutual Fund",
        "scheme_type": "Open Ended Schemes",
        "scheme_category": "Equity Scheme",
        "scheme_sub_category": "Flexi Cap Fund",
        "risk_grade": "Very High",
        "aum_cr": 52104.90,
        "expense_ratio": 0.76,
        "launch_date": "2013-01-01",
    },
    # Debt Funds
    {
        "scheme_code": 119233,
        "scheme_name": "HDFC Short Term Debt Fund - Direct Plan - Growth",
        "fund_house": "HDFC Mutual Fund",
        "scheme_type": "Open Ended Schemes",
        "scheme_category": "Debt Scheme",
        "scheme_sub_category": "Short Duration Fund",
        "risk_grade": "Moderate",
        "aum_cr": 13892.60,
        "expense_ratio": 0.28,
        "launch_date": "2013-01-01",
    },
    {
        "scheme_code": 119780,
        "scheme_name": "SBI Magnum Gilt Fund - Direct Plan - Growth",
        "fund_house": "SBI Mutual Fund",
        "scheme_type": "Open Ended Schemes",
        "scheme_category": "Debt Scheme",
        "scheme_sub_category": "Gilt Fund",
        "risk_grade": "Moderate",
        "aum_cr": 9214.30,
        "expense_ratio": 0.43,
        "launch_date": "2013-01-01",
    },
    {
        "scheme_code": 119823,
        "scheme_name": "ICICI Prudential Corporate Bond Fund - Direct Plan - Growth",
        "fund_house": "ICICI Prudential Mutual Fund",
        "scheme_type": "Open Ended Schemes",
        "scheme_category": "Debt Scheme",
        "scheme_sub_category": "Corporate Bond Fund",
        "risk_grade": "Low to Moderate",
        "aum_cr": 21543.80,
        "expense_ratio": 0.35,
        "launch_date": "2013-01-01",
    },
    # Hybrid Funds
    {
        "scheme_code": 120465,
        "scheme_name": "ICICI Prudential Balanced Advantage Fund - Direct Plan - Growth",
        "fund_house": "ICICI Prudential Mutual Fund",
        "scheme_type": "Open Ended Schemes",
        "scheme_category": "Hybrid Scheme",
        "scheme_sub_category": "Dynamic Asset Allocation",
        "risk_grade": "Very High",
        "aum_cr": 47821.30,
        "expense_ratio": 0.76,
        "launch_date": "2013-01-01",
    },
    {
        "scheme_code": 119683,
        "scheme_name": "HDFC Balanced Advantage Fund - Direct Plan - Growth",
        "fund_house": "HDFC Mutual Fund",
        "scheme_type": "Open Ended Schemes",
        "scheme_category": "Hybrid Scheme",
        "scheme_sub_category": "Dynamic Asset Allocation",
        "risk_grade": "Very High",
        "aum_cr": 88321.40,
        "expense_ratio": 0.82,
        "launch_date": "2013-01-01",
    },
    {
        "scheme_code": 119822,
        "scheme_name": "SBI Equity Hybrid Fund - Direct Plan - Growth",
        "fund_house": "SBI Mutual Fund",
        "scheme_type": "Open Ended Schemes",
        "scheme_category": "Hybrid Scheme",
        "scheme_sub_category": "Aggressive Hybrid Fund",
        "risk_grade": "Very High",
        "aum_cr": 62418.70,
        "expense_ratio": 0.67,
        "launch_date": "2013-01-01",
    },
    # Index Funds
    {
        "scheme_code": 120716,
        "scheme_name": "UTI Nifty 50 Index Fund - Direct Plan - Growth",
        "fund_house": "UTI Mutual Fund",
        "scheme_type": "Open Ended Schemes",
        "scheme_category": "Other Scheme",
        "scheme_sub_category": "Index Funds",
        "risk_grade": "Very High",
        "aum_cr": 18472.60,
        "expense_ratio": 0.20,
        "launch_date": "2013-01-01",
    },
    {
        "scheme_code": 120684,
        "scheme_name": "HDFC Index Fund Nifty 50 Plan - Direct Plan - Growth",
        "fund_house": "HDFC Mutual Fund",
        "scheme_type": "Open Ended Schemes",
        "scheme_category": "Other Scheme",
        "scheme_sub_category": "Index Funds",
        "risk_grade": "Very High",
        "aum_cr": 12983.40,
        "expense_ratio": 0.20,
        "launch_date": "2013-01-01",
    },
    # Sectoral
    {
        "scheme_code": 119028,
        "scheme_name": "SBI Banking & Financial Services Fund - Direct Plan - Growth",
        "fund_house": "SBI Mutual Fund",
        "scheme_type": "Open Ended Schemes",
        "scheme_category": "Equity Scheme",
        "scheme_sub_category": "Sectoral Fund - Banking",
        "risk_grade": "Very High",
        "aum_cr": 7234.80,
        "expense_ratio": 0.62,
        "launch_date": "2015-02-26",
    },
    {
        "scheme_code": 120819,
        "scheme_name": "Kotak Infrastructure & Economic Reform Fund - Direct Plan - Growth",
        "fund_house": "Kotak Mahindra Mutual Fund",
        "scheme_type": "Open Ended Schemes",
        "scheme_category": "Equity Scheme",
        "scheme_sub_category": "Sectoral Fund - Infrastructure",
        "risk_grade": "Very High",
        "aum_cr": 3418.20,
        "expense_ratio": 0.71,
        "launch_date": "2013-01-01",
    },
    # Liquid Funds
    {
        "scheme_code": 119189,
        "scheme_name": "HDFC Liquid Fund - Direct Plan - Growth",
        "fund_house": "HDFC Mutual Fund",
        "scheme_type": "Open Ended Schemes",
        "scheme_category": "Debt Scheme",
        "scheme_sub_category": "Liquid Fund",
        "risk_grade": "Low",
        "aum_cr": 71293.80,
        "expense_ratio": 0.20,
        "launch_date": "2013-01-01",
    },
    {
        "scheme_code": 119597,
        "scheme_name": "SBI Liquid Fund - Direct Plan - Growth",
        "fund_house": "SBI Mutual Fund",
        "scheme_type": "Open Ended Schemes",
        "scheme_category": "Debt Scheme",
        "scheme_sub_category": "Liquid Fund",
        "risk_grade": "Low",
        "aum_cr": 58742.30,
        "expense_ratio": 0.21,
        "launch_date": "2013-01-01",
    },
    {
        "scheme_code": 120573,
        "scheme_name": "Axis Liquid Fund - Direct Plan - Growth",
        "fund_house": "Axis Mutual Fund",
        "scheme_type": "Open Ended Schemes",
        "scheme_category": "Debt Scheme",
        "scheme_sub_category": "Liquid Fund",
        "risk_grade": "Low",
        "aum_cr": 32187.50,
        "expense_ratio": 0.19,
        "launch_date": "2013-01-01",
    },
    {
        "scheme_code": 120503,
        "scheme_name": "ICICI Prudential Liquid Fund - Direct Plan - Growth",
        "fund_house": "ICICI Prudential Mutual Fund",
        "scheme_type": "Open Ended Schemes",
        "scheme_category": "Debt Scheme",
        "scheme_sub_category": "Liquid Fund",
        "risk_grade": "Low",
        "aum_cr": 44823.70,
        "expense_ratio": 0.20,
        "launch_date": "2013-01-01",
    },
]


def main():
    df = pd.DataFrame(FUND_MASTER_DATA)
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(OUTPUT_PATH, index=False)
    print(f"fund_master.csv created at: {OUTPUT_PATH}")
    print(f"Shape: {df.shape}")
    print(f"\nUnique Fund Houses  : {df['fund_house'].nunique()}")
    print(f"Unique Categories   : {df['scheme_category'].nunique()}")
    print(f"Unique Sub-Categories: {df['scheme_sub_category'].nunique()}")
    print(f"Unique Risk Grades  : {df['risk_grade'].nunique()}")
    print(f"\nFund House Counts:\n{df['fund_house'].value_counts().to_string()}")
    print(f"\nCategory Counts:\n{df['scheme_category'].value_counts().to_string()}")
    print(f"\nSub-Category Counts:\n{df['scheme_sub_category'].value_counts().to_string()}")
    print(f"\nRisk Grade Counts:\n{df['risk_grade'].value_counts().to_string()}")


if __name__ == "__main__":
    main()
